//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BavuaDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BavuaEntities : DbContext
    {
        public BavuaEntities()
            : base("name=BavuaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Cards_in_cash> Cards_in_cash { get; set; }
        public virtual DbSet<Cashes> Cashes { get; set; }
        public virtual DbSet<Cashes_in_game> Cashes_in_game { get; set; }
        public virtual DbSet<Game_board> Game_board { get; set; }
        public virtual DbSet<Save_games> Save_games { get; set; }
        public virtual DbSet<Summits> Summits { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
