//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BavuaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_board
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_board()
        {
            this.Save_games = new HashSet<Save_games>();
        }
    
        public int game_board_code { get; set; }
        public int game_board_value_location0 { get; set; }
        public int game_board_value_location1 { get; set; }
        public int game_board_value_location2 { get; set; }
        public int game_board_value_location3 { get; set; }
        public int game_board_value_location4 { get; set; }
        public int game_board_value_location5 { get; set; }
        public int game_board_value_location6 { get; set; }
        public int game_board_value_location7 { get; set; }
        public int game_board_value_location8 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Save_games> Save_games { get; set; }
    }
}
