//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BavuaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Save_games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Save_games()
        {
            this.Cashes_in_game = new HashSet<Cashes_in_game>();
        }
    
        public int save_game_code { get; set; }
        public int save_game_board_code { get; set; }
        public System.DateTime save_game_date { get; set; }
        public bool save_game_isTimer { get; set; }
        public System.DateTime save_game_timePoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cashes_in_game> Cashes_in_game { get; set; }
        public virtual Game_board Game_board { get; set; }
    }
}
